source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Alamofire'	
pod 'RSBarcodes_Swift'

# set the ONLY_ACTIVE_ARCH to NO
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end

# disable asset compilation by cocoapods
system "find Pods -type f -name Pods-resources.sh -exec sed -i .bak 's/  find \"/  # find \"/g' {} \\;"
end