source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

def shared_pods
    pod 'SwiftyJSON'
    pod 'Alamofire'
end

target 'GoodWatchHuntingApp' do
    pod 'RSBarcodes_Swift'
    shared_pods
end

target 'GoodWatchHuntingApp WatchKit Extension' do
    platform :watchos, '2.0'
    shared_pods
end

# set the ONLY_ACTIVE_ARCH to NO
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end

# disable asset compilation by cocoapods
system "find Pods -type f -name Pods-resources.sh -exec sed -i .bak 's/  find \"/  # find \"/g' {} \\;"
end